# Generated by Django 2.2 on 2020-02-26 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_dogtinder', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='terms',
        ),
    ]
