# Generated by Django 2.2 on 2020-02-26 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_dogtinder', '0002_remove_user_terms'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dog',
            old_name='dog',
            new_name='user',
        ),
    ]
