# Generated by Django 2.2 on 2020-02-27 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_dogtinder', '0003_auto_20200226_1556'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='app_dogtinder.Dog')),
            ],
        ),
    ]
