# Generated by Django 2.2 on 2020-02-27 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_dogtinder', '0004_ratinglist'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='terms',
            field=models.BooleanField(default=True, error_messages={'required': 'You must accept the terms and conditions.'}),
            preserve_default=False,
        ),
    ]
